[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
banger_program = "CYu4zKWC3tNGaJkime2PagfjPCski5YAvS8DwhX25d3o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pdawg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
